//! fail exec

func returns_func(value, info) /* -> Func */ {
	println("called outer with value: `", value, "`")
	println("\t", info)

	func inner(value) {
		println("called inner with value: `", value, "`")
		println("\t", info)
	}

	inner
}

const info = ()
returns_func(1, "This should work")
returns_func(0, "This should not work")(false)
